version: "3.0"

services:
  engine:
    build:
      context: ./engine
      dockerfile: Dockerfile
    ports:
      - "8888:8000"
    volumes:
      - ./engine:/home/engine
  mock:
    build:
      context: ./mocksite
      dockerfile: Dockerfile
    ports:
      - "3232:3000"
    volumes:
      - "./mocksite:/app"
      - "/app/node_modules"
